### ISSUE TITLE
Increase graph duration

### ISSUE THREAD

**Issue by dave4445** [centerclick/feedback#14]
Graphs longer than 1 day would be good

**Comment by dave4445** [comment]
now 7 days.  released 1.21

**Comment by srob1** [comment]
Is it possible for the graph duration to be dynamic, so that it's the number of days since reboot rounded up with a max of 7 rather than always 7 even when there's fewer days of data ?  After reboot, the entire graph is being smashed into 1/7 of the space, which isn't very useful.  While the device won't be rebooted that often, it does happen periodically for things like firmware update and IP addressing changes.

**Comment by dave4445** [comment]
when first upgrading into >=1.21 the previous data from <1.21 is still there, so only 1 day of that.  after 7 days all the old data will be pushed out.  when rebooting/upgrading  from >= 1.21 to >=1.21 you'd have all 7 days.

**Comment by sgrayban** [comment]
I would also change the height of the graph as well. Very hard to read the x/y labels
