### ISSUE TITLE
SNMP Monitoring with RFC5907 MIB

### ISSUE THREAD

**Issue by avluis** [centerclick/feedback#59]
Would like to see monitoring via SNMP (v2/v3 preferred) as well as minimal ability to configure what it presents (optionally support changing community settings)

**Comment by dave4445** [comment]
Are you looking for a specific NTP MiB or just genetic system ones?

**Comment by avluis** [comment]
If [rfc5907](https://www.ietf.org/rfc/rfc5907.txt) {NTPv4} is considered alongside standard (system) OIDs I'd be a happy camper

**Comment by dave4445** [comment]
NOTE: multiple people are now asking for this

**Comment by lump** [comment]
I just ordered an NTP250 for my homelab.  I have been perusing the documentation in preparation, and so far, I like everything about this appliance except that it seems to be missing SNMP and a legit serial port (which I believe might be a better place for a PPS signal than an unprotected circuit).  SNMP would be a great addition that I would most definitely use to graph from Observium and alert thresholds from Nagios.

**Comment by dave4445** [comment]
Thanks Troy, I started on this a few months ago and adding system MIBs isn't a big deal, however finding something for rfc5907 was a bit more troublesome.  Threr's a PoC AgentX that implements parts of it out there from a GSOC project but it's not really useful as is.  Implementing this MIB from scratch would be quite time consuming

**Comment by lump** [comment]
Wow, I was just chiming in with my +1 for the record.  Now I look forward to this product even more because talking with the developer at this level makes it even more amazing.  Thank you for your responsiveness!

I agree, to write it from scratch would be painful.  I was hoping you were running [ISC NTPd](https://www.ntp.org/) under the covers and could simply turn on the [ntpsnmpd](https://github.com/ntp-project/ntp/blob/master-no-authorname/ntpsnmpd/ntpsnmpd.c) daemon after installing [net-snmp](http://www.net-snmp.org/) and turning on the master agentx socket.  But if you're doing closed-source stuff, I'm not sure what to say.

**Comment by dave4445** [comment]
Yes, but if you look closely at that ntpsnmpd it's just a proof of concept and very incomplete, only implementing a few of the MIB objects.  hasn't been touched in 8+ years.

**Comment by lump** [comment]
Oh, sigh, that's sad.  You're right, it is basically an abandoned Google Summer of Code project.

Now that I think of it, my Observium metrics graphing uses a fork of the check_mk agent instead of getting NTP stats over SNMP.

![image](https://user-images.githubusercontent.com/280484/219986797-77c052cd-c32a-4b39-bfb9-32e8c3b84451.png)

Not that I don't like the NTP250's graphs.  I just like to centralize metrics graphing.

But, to get these kinds of stats from an _appliance_, it might be better to use a standard like SNMP instead of having to support any number of kinds of agents.  If I am allowed to keep asking, the next thing I'd ask for is a page that lists stats that [Prometheus](https://prometheus.io/docs/introduction/overview/) can scrape (and then that [Grafana](https://grafana.com/) can easily graph).  But I can probably write a transform for the already provided JSONs for Prometheus.  SNMP is a lot lower level.

**Comment by dave4445** [comment]
SNMP is now available in v2.7 minus the NTP mib

**Comment by lump** [comment]
Wow, thank you!  It looks like my device already got the update!

I enabled SNMP, and the device is answering!  I already added it to Observium.   It is nice to at least have the system resource graphs for now, thank you.

**Comment by avluis** [comment]
Received the update recently and enabled the feature; thank you for implementing this!

**Comment by gidig** [comment]
Great new feature, thanks.

How about location/contact and such basic infos?

**Comment by dave4445** [comment]
FYI: Prometheus metrics exporter coming in #101

**Comment by lump** [comment]
This is what Observium's Overview page looks like.  CPU consumption and CPU _load_ averages might be nice to include just to summarize how much work the machine is doing versus the available hardware it has.  I am willing to bet it is mostly bored with an extremely low load.

![observium-clock](https://user-images.githubusercontent.com/280484/235970324-5ca99129-531f-4552-b320-9718f5453338.png)
